In [5]:
import numpy as np

In [6]:
# -- 3.1 --

In [2]:
list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]

In [4]:
arr = np.array(list)

In [11]:
print("arr * 4:", arr * 4)

arr * 4: [ 80 108  36  48 124  68  16 200 156 140]


In [13]:
print("mean:", np.mean(arr))

mean: 24.4


In [14]:
print("median:", np.median(arr))

median: 23.5


In [15]:
print("standard deviation:", np.std(arr))

standard deviation: 13.828955130450023


In [17]:
min_index = np.argmin(arr)
max_index = np.argmax(arr)

print("index of smallest value:", min_index)
print("index of largest value:", max_index)

index of smallest value: 6
index of largest value: 7


In [18]:
print("smallest value:", arr[min_index])
print("largest value:", arr[max_index])

smallest value: 4
largest value: 50


In [19]:
print("smallest value:", np.min(arr))
print("largest value:", np.max(arr))

smallest value: 4
largest value: 50


In [23]:
greater_than_20 = arr[arr > 20]

In [24]:
print("new_arr:", greater_than_20)

new_arr: [27 31 50 39 35]


In [25]:
# -- 3.2 --

In [31]:
matrix = np.array([
[5, 12, 17, 9],
[8, 21, 14, 3],
[6, 13, 19, 11]
])

In [35]:
print("shape:", matrix.shape)
print("row:", matrix.shape[0])
print("column:", matrix.shape[1])

shape: (3, 4)
row: 3
column: 4


In [36]:
print("third column:", matrix[:,2])

third column: [17 14 19]


In [37]:
print("second row:", matrix[1])

second row: [ 8 21 14  3]


In [38]:
print("matrix * 2:", matrix * 2)

matrix * 2: [[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]


In [39]:
print("mean of each column:", np.mean(matrix,axis=0))

mean of each column: [ 6.33333333 15.33333333 16.66666667  7.66666667]


In [40]:
print("overall mean:", np.mean(matrix))

overall mean: 11.5


In [41]:
print("max in each row:", np.max(matrix, axis=1))
print("min in each column:", np.min(matrix, axis=0))

max in each row: [17 21 19]
min in each column: [ 5 12 14  3]


In [46]:
new_matrix = matrix.flatten()
print("new_matrix:", new_matrix)
print("new_matrix shape:", new_matrix.shape)

new_matrix: [ 5 12 17  9  8 21 14  3  6 13 19 11]
new_matrix shape: (12,)


In [49]:
min_index_new_matrix = np.argmin(new_matrix)
max_index_new_matrix = np.argmax(new_matrix)

print("index of smallest value in new_matrix:", 
      min_index_new_matrix)
print("index of largest value in new_matrix:", 
      max_index_new_matrix)

index of smallest value in new_matrix: 7
index of largest value in new_matrix: 5


In [54]:
min_index = np.unravel_index(min_index_new_matrix, matrix.shape)
max_index = np.unravel_index(max_index_new_matrix, matrix.shape)

print("min coordinates", min_index)
print("max coordinates", max_index)


min coordinates (1, 3)
max coordinates (1, 1)


In [55]:
greater_than_15 = matrix[matrix > 15]
print("matrix greater_than_15:" ,greater_than_15)

matrix greater_than_15: [17 21 19]


In [56]:
print("sorted array:", np.sort(matrix, axis=1))

sorted array: [[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [61]:
# -- 4 --

In [62]:
arr = np.array([
[2, 3, 5],
[14, 6, 8],
[11, 13, 17],
[7, 10, 13]
])

In [65]:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n) + 1)):
        if n % i == 0:
            return False
    return True

In [66]:
def rows_at_least_one_prime_number(arr):
    prime_mask = np.vectorize(is_prime)(arr)
    row_mask = np.any(prime_mask, axis = 1)
    return arr[row_mask]

In [67]:
print(rows_at_least_one_prime_number(arr))

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [68]:
# -- 5 --

In [70]:
def checkerboard():
    board = np.zeros((8,8),dtype=int)
    board[::2, ::2] = 1
    board[1::2, 1::2] = 1
    return board

print(checkerboard())

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [74]:
def reverse_checkerboard():
    board = np.zeros((8,8),dtype=int)
    board[::2, 1::2] = 1
    board[1::2, ::2] = 1
    return board

print(reverse_checkerboard())

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [75]:
# -- 6 --

In [84]:
def expansion(arr, spaces):
    space_number = " " * spaces
    return np.array([space_number.join(word) for word in arr])

In [86]:
universe = np.array(["galaxy", "clusters"])

In [87]:
expansion(universe, 1)

array(['g a l a x y', 'c l u s t e r s'], dtype='<U15')

In [88]:
expansion(universe, 2)

array(['g  a  l  a  x  y', 'c  l  u  s  t  e  r  s'], dtype='<U22')

In [89]:
# -- 7 --

In [90]:
def secondDimmest(stars):
    sorted_row = np.sort(stars, axis=1)
    return sorted_row[:,-2]

In [99]:
np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))
print(stars)

[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]


In [100]:
secondDimmest(stars)

array([1889, 1647, 1138, 1863, 1592])